// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {
    IAcceptanceDeployer,
    IMockUsdt,
    DovizirSystem
} from "./interfaces/IAcceptanceDeployer.sol";
import {IIouToken, IMemberRegistry, IReservePool, IInsuranceFund, ISarrafRegistry, INoteVault} from "./interfaces/IDovizir.sol";

/// @title StubDeployer — COMPILE-CHECK STUB ONLY. NOT AN IMPLEMENTATION.
/// @notice This exists solely so the referee suite compiles and runs
/// standalone (`forge build` / `forge test` with no arm attached). Every
/// protocol call on the returned system reverts with "STUB", so every
/// acceptance test FAILS against it — that is expected and correct.
/// Arms DO NOT edit this file; they provide their own IAcceptanceDeployer and
/// point the suite at it via the DOVIZIR_DEPLOYER env var (see README.md).
contract Stub {
    fallback() external payable {
        revert("STUB");
    }

    receive() external payable {
        revert("STUB");
    }
}

contract StubDeployer is IAcceptanceDeployer {
    function deploy() external override returns (DovizirSystem memory system) {
        // deploy() itself succeeds so that each test fails individually at its
        // first protocol interaction (clearer signal than a setUp-wide error).
        system = DovizirSystem({
            usdt: IMockUsdt(address(new Stub())),
            iouToken: IIouToken(address(new Stub())),
            memberRegistry: IMemberRegistry(address(new Stub())),
            reservePool: IReservePool(address(new Stub())),
            insuranceFund: IInsuranceFund(address(new Stub())),
            sarrafRegistry: ISarrafRegistry(address(new Stub())),
            noteVault: INoteVault(address(new Stub()))
        });
    }
}
