#!/usr/bin/env node
// Generates app/tokens.css (Tailwind v4 @theme) from the design system source
// of truth at .brewing/docs/design-system.json. The output is checked in;
// rerun with `pnpm --filter @dovizir/web generate:tokens` after token changes.
//
// Semantic slots are resolved by palette entry NAME so every hex value flows
// from the JSON — no colors are hardcoded here or in components.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ds = JSON.parse(
  readFileSync(resolve(here, "../../../.brewing/docs/design-system.json"), "utf8"),
);

const color = (name) => {
  const entry = ds.palette.find((p) => p.name === name);
  if (!entry) throw new Error(`palette entry not found: ${name}`);
  return entry.hex;
};
const border = (name) => {
  const entry = ds.borders.find((b) => b.name === name);
  if (!entry) throw new Error(`border entry not found: ${name}`);
  return entry.value;
};

// Light / dark semantic surfaces (dark layers #121212 -> #272727 -> #2E2E2E).
const light = {
  background: color("White"),
  surface: color("Surface Light"),
  "surface-alt": color("Surface Light Alt"),
  foreground: color("Ink"),
  muted: color("Muted Gray"),
  border: border("default"),
  accent: color("Brand Blue"),
};
const dark = {
  background: color("Surface Dark"),
  surface: color("Elevated Dark"),
  "surface-alt": color("Card Dark"),
  foreground: color("Text on Dark"),
  muted: color("Disabled Gray"),
  border: border("dark"),
  accent: color("Light Blue"),
};
const universal = {
  primary: color("Primary Blue"),
  success: color("Success Green"),
  danger: color("Error Red"),
  warning: color("Amber"),
  focus: border("focus"),
};

const vars = (obj, indent = "  ") =>
  Object.entries(obj)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join("\n");

const radii = ds.radii.map((r) => `  --radius-${r.name}: ${r.value};`).join("\n");
const spacing = ds.spacing
  .map((s) => `  --spacing-${s.name}: ${s.value};`)
  .join("\n");
const shadows = ds.shadows
  .map((s) => `  --shadow-${s.name}: ${s.value};`)
  .join("\n");
const motion = ds.motion
  .map((m) => `  --ease-${m.name}: ${m.easing};\n  --duration-${m.name}: ${m.ms}ms;`)
  .join("\n");

// Font roles from the JSON (Roboto body, Inter headings); Vazirmatn is the
// Farsi/RTL face loaded via next/font in layout.tsx.
const bodyFamily = ds.typography.families.find((f) => f.role === "body").family;
const headingFamily = ds.typography.families.find((f) => f.role === "headings").family;
const slug = (f) => f.toLowerCase().replace(/\s+/g, "-");

const css = `/* GENERATED by scripts/generate-tokens.mjs from .brewing/docs/design-system.json.
 * Do not edit by hand — rerun \`pnpm --filter @dovizir/web generate:tokens\`. */

:root {
${vars(light)}
}

@media (prefers-color-scheme: dark) {
  :root {
${vars(dark, "    ")}
  }
}

@theme inline {
  /* semantic colors (light/dark via the vars above) */
  --color-background: var(--background);
  --color-surface: var(--surface);
  --color-surface-alt: var(--surface-alt);
  --color-foreground: var(--foreground);
  --color-muted: var(--muted);
  --color-border: var(--border);
  --color-accent: var(--accent);

  /* universal roles */
  --color-primary: ${universal.primary};
  --color-primary-foreground: ${light.background};
  --color-success: ${universal.success};
  --color-danger: ${universal.danger};
  --color-warning: ${universal.warning};
  --color-focus: ${universal.focus};

  /* radii */
${radii}

  /* spacing scale */
${spacing}

  /* shadows */
${shadows}

  /* motion */
${motion}

  /* type — ${bodyFamily} body, ${headingFamily} headings, Vazirmatn for fa */
  --font-body: var(--font-${slug(bodyFamily)}), var(--font-vazirmatn), system-ui, sans-serif;
  --font-heading: var(--font-${slug(headingFamily)}), var(--font-vazirmatn), system-ui, sans-serif;
}
`;

writeFileSync(resolve(here, "../app/tokens.css"), css);
console.log("wrote app/tokens.css");
