// Dovizir — tailwind theme, generated by dash from the
// EXTRACTED design system (found tokens verbatim; primary/accent ramps DERIVED).
// Do not hand-edit — re-export from dash.
import type { Config } from "tailwindcss";
export default {
  content: [],
  theme: {
    extend: {
      colors: {
        primary: { // ramp DERIVED from found #2196F3 (500 = found value)
          DEFAULT: "#2196F3",
          50: "#F2F9FE",
          100: "#E0F0FD",
          200: "#BCE0FB",
          300: "#94CDF9",
          400: "#5FB3F6",
          500: "#2196F3",
          600: "#1E82D3",
          700: "#1A6CAE",
          800: "#165689",
          900: "#133F64",
          950: "#102C43",
        },
        accent: { // ramp DERIVED from found #90CAF9 (500 = found value)
          DEFAULT: "#90CAF9",
          50: "#F8FCFF",
          100: "#EFF8FE",
          200: "#DEEFFD",
          300: "#CAE6FC",
          400: "#AFD9FB",
          500: "#90CAF9",
          600: "#7DAFD8",
          700: "#6890B2",
          800: "#52728C",
          900: "#3D5366",
          950: "#2A3845",
        },
        bg: "#FFFFFF",
        surface: "#F5F5F5",
        text: "#171717",
        success: "#4CAF50",
        warn: "#E53935",
        danger: "#E53935",
        border: "#E0E0E0",
      },
      fontFamily: {
      "body": ["Roboto"],
      "headings": ["Poppins"],
      "mono": ["Geist Mono"],
      },
      spacing: {
      "xs": "4px",
      "sm": "8px",
      "md": "12px",
      "lg": "16px",
      "xl": "24px",
      "2xl": "32px",
      },
      borderRadius: {
      "xs": "4px",
      "sm": "8px",
      "md": "12px",
      "lg": "16px",
      "pill": "100px",
      },
      boxShadow: {
      "sm": "0 1px 3px rgba(0,0,0,.08)",
      "card": "0 3px 16px rgba(0,0,0,.08)",
      "md": "0 7px 34px rgba(0,0,0,.12)",
      "lg": "0 18px 28px rgba(0,0,0,.14)",
      "topbar": "0 -1px 16px rgba(0,0,0,.12)",
      },
      transitionDuration: {
      "fast": "100ms",
      "standard": "300ms",
      "emphasized": "200ms",
      "smooth": "200ms",
      },
    },
  },
} satisfies Config;
