#!/usr/bin/env node
// Regenerates src/abi/*.ts from the forge build output of @dovizir/contracts.
//
// Usage:  cd packages/contracts && forge build   (forge lives at ~/.foundry/bin)
//         node packages/sdk/scripts/generate-abis.mjs
//
// The generated files are checked in so the web app builds without foundry.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsOut = resolve(here, "../../contracts/out");
const abiDir = resolve(here, "../src/abi");

/** contract name in out/<File>.sol/<Name>.json -> exported const name */
const CONTRACTS = {
  IouToken: "iouTokenAbi",
  MemberRegistry: "memberRegistryAbi",
  ReservePool: "reservePoolAbi",
  InsuranceFund: "insuranceFundAbi",
  SarrafRegistry: "sarrafRegistryAbi",
  NoteVault: "noteVaultAbi",
  MockUsdt: "mockUsdtAbi",
};

mkdirSync(abiDir, { recursive: true });

const index = [];
for (const [contract, exportName] of Object.entries(CONTRACTS)) {
  const artifactPath = join(contractsOut, `${contract}.sol`, `${contract}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const file = join(abiDir, `${contract}.ts`);
  const body =
    `// Generated by packages/sdk/scripts/generate-abis.mjs from\n` +
    `// packages/contracts/out/${contract}.sol/${contract}.json — do not edit by hand.\n` +
    `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(file, body);
  index.push(`export { ${exportName} } from "./${contract}";`);
  console.log(`wrote src/abi/${contract}.ts (${artifact.abi.length} items)`);
}
writeFileSync(join(abiDir, "index.ts"), index.join("\n") + "\n");
console.log("wrote src/abi/index.ts");
